import type { Stylable } from '../../types';

export type IconName =
  | 'sun'
  | 'moon'
  | 'home'
  | 'activity'
  | 'workout-run'
  | 'workout-walk'
  | 'workout-cycle'
  | 'workout-strength'
  | 'workout-hiit'
  | 'workout-yoga'
  | 'workout-swim'
  | 'workout-hike'
  | 'info'
  | 'visitor-avatar'
  | 'edit'
  | 'refresh'
  | 'zoom-in'
  | 'zoom-out'
  | 'clock'
  | 'calendar'
  | 'timer'
  | 'mail'
  | 'bookmark'
  | 'bookmark-filled'
  | 'chevron-left'
  | 'chevron-down'
  | 'chevron-up'
  | 'more-horizontal'
  | 'sidebar-expand'
  | 'sidebar-collapse'
  | 'close'
  | 'trash'
  | 'settings'
  | 'key'
  | 'auth-sign-in'
  | 'auth-sign-out'
  | 'glucose'
  | 'server'
  | 'github'
  | 'desktop'
  | 'smartphone'
  | 'lightbulb'
  | 'dashboard-grid'
  | 'veno-wordmark'
  | 'veno-glucose-indicator'
  | 'veno-logo';

export type IconProps = Stylable & {
  icon: IconName;
  title?: string;
  size?: string;
};
